app/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static

from app import settings


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("main.urls", namespace="main")),
    path("", include("goods.urls", namespace="catalog")),
    path("", include("goods.urls", namespace="action")),
    path("", include("goods.urls", namespace="new_goods")),
    path("user/", include("users.urls", namespace="user")),
    path("cart/", include("carts.urls", namespace="cart")),
    path("orders/", include("orders.urls", namespace="orders")),
]


if settings.DEBUG:
    urlpatterns += [
        path("__debug__/", include("debug_toolbar.urls")),
    ]
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

orders/urls.py
from django.urls import path
from orders import views

app_name = 'orders'

urlpatterns = [
    path('create_order/', views.create_order, name='create_order'),
    path('qr_code/<int:order_id>/', views.qr_code, name='qr_code'),
]

orders/models.py
from django.db import models
from goods.models import Products

from users.models import User


class OrderitemQueryset(models.QuerySet):
    
    def total_price(self):
        return sum(cart.products_price() for cart in self)
    
    def total_quantity(self):
        if self:
            return sum(cart.quantity for cart in self)
        return 0

class Order(models.Model):
    first_name = models.CharField(max_length=150, verbose_name="Имя получателя", blank=True, null=True, default=None)
    last_name = models.CharField(max_length=150, verbose_name="Фамилия получателя", blank=True, null=True, default=None)
    user = models.ForeignKey(to=User, on_delete=models.SET_DEFAULT, blank=True, null=True, verbose_name="Пользователь", default=None)
    created_timestamp = models.DateTimeField(auto_now_add=True, verbose_name="Дата создания заказа")
    phone_number = models.CharField(max_length=20, verbose_name="Номер телефона")
    delivery_address = models.TextField(null=True, blank=True, verbose_name="Адрес доставки")
    is_paid = models.BooleanField(default=False, verbose_name="Оплачено")
    status = models.CharField(max_length=50, default='В обработке', verbose_name="Статус заказа")
    qr_image = models.ImageField(upload_to='qr_codes/', null=True, blank=True, verbose_name="QR-код")  # Новое поле для QR-кода
    comment = models.TextField(blank=True, null=True, verbose_name="Комментарий к заказу")
    email = models.EmailField(verbose_name="Email получателя", blank=True, null=True, default=None)

    class Meta:
        db_table = "order"
        verbose_name = "Заказ"
        verbose_name_plural = "Заказы"

    def __str__(self):
        if self.first_name and self.last_name:
            return f"Заказ № {self.pk} | Покупатель {self.first_name} {self.last_name}"
        else:
            return f"Заказ № {self.pk} | Покупатель {self.user.first_name} {self.user.last_name}"


class OrderItem(models.Model):
    order = models.ForeignKey(to=Order, on_delete=models.CASCADE, verbose_name="Заказ")
    product = models.ForeignKey(to=Products, on_delete=models.SET_DEFAULT, null=True, verbose_name="Продукт", default=None)
    name = models.CharField(max_length=150, verbose_name="Название")
    price = models.DecimalField(max_digits=7, decimal_places=2, verbose_name="Цена")
    quantity = models.PositiveIntegerField(default=0, verbose_name="Количество")
    created_timestamp = models.DateTimeField(auto_now_add=True, verbose_name="Дата продажи")


    class Meta:
        db_table = "order_item"
        verbose_name = "Проданный товар"
        verbose_name_plural = "Проданные товары"

    objects = OrderitemQueryset.as_manager()

    def products_price(self):
        return round(self.price * self.quantity, 2)

    def __str__(self):
        return f"Товар {self.name} | Заказ № {self.order.pk}"

orders/views.py
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.db import transaction
from django.forms import ValidationError
from django.shortcuts import redirect, render
import qrcode


from carts.models import Cart

from main.forms import ContactForm
from orders.form import CreateOrderForm
from orders.models import Order, OrderItem

from io import BytesIO
from django.core.files.base import ContentFile
from django.urls import reverse


@login_required
def create_order(request):
    initial = {
        'first_name': request.user.first_name,
        'last_name': request.user.first_name,
        'email': request.user.first_name,
        'phone_number': request.user.first_name,
        }

    form = CreateOrderForm(initial=initial)
     


    if request.method == 'POST':
        form = CreateOrderForm(data=request.POST)
        if form.is_valid():
            try:
                with transaction.atomic():  # Обеспечение атомарности операции
                    user = request.user
                    cart_items = Cart.objects.filter(user=user)

                    if not cart_items.exists():
                        messages.warning(request, "Ваша корзина пуста.")
                        return redirect("goods:catalog")

                    # Создание заказа
                    order = Order.objects.create(
                        user=user,
                        first_name = form.cleaned_data['first_name'],
                        last_name = form.cleaned_data['last_name'],
                        phone_number=form.cleaned_data['phone_number'],
                        delivery_address=form.cleaned_data['delivery_address'],
                        comment = form.cleaned_data.get('comment', None),
                        email = form.cleaned_data['email'],
                    )

                    total_amount = 0  # Общая сумма заказа

                    # Создание заказанных товаров
                    for cart_item in cart_items:
                        product = cart_item.product
                        name = product.name
                        price = product.sell_price()
                        quantity = cart_item.quantity

                        if product.quantity < quantity:
                            raise ValidationError(f"Недостаточно товара {name}. В наличии - {product.quantity}")

                        # Создание `OrderItem` для каждого товара в корзине
                        OrderItem.objects.create(
                            order=order,
                            product=product,
                            name=name,
                            price=price,
                            quantity=quantity,
                        )

                        product.quantity -= quantity  # Уменьшение количества товара
                        product.save()  # Сохранение изменений в базе данных

                        total_amount += price * quantity  # Добавление к общей сумме

                    # Генерация QR-кода
                    total_amount_in_cents = int(total_amount * 100)

                    qr_data = (
                        f"ST00012|Name=Спорт Лайн|PersonalAcc=40817810711524044721|"
                        f"BankName=ВТБ|BIC=043601968|CorrespAcc=30101810422023601968|"
                        f"Currency=RUB|Sum={total_amount_in_cents}|Purpose=Оплата заказа №{order.id}"
                    )

                    buffer = BytesIO()
                    qr = qrcode.make(qr_data)
                    qr.save(buffer, format="PNG")

                    qr_image_file = ContentFile(buffer.getvalue(), 'qr_code.png')  # Создание файла
                    order.qr_image.save('qr_code.png', qr_image_file, save=True)

                    cart_items.delete()  # Очистка корзины после заказа

                    messages.success(request, "Заказ успешно оформлен!")  # Уведомление

                    # Перенаправление на страницу с QR-кодом
                    return redirect(reverse("orders:qr_code", kwargs={'order_id': order.id}))
                    
            except ValidationError as e:
                messages.warning(request, str(e))
                return redirect("orders:create_order")

    else:
        initial = {
            'first_name': request.user.first_name,
            'last_name': request.user.last_name,
            'email': request.user.email,
            'phone_number': request.user.phone_number,
            }

        form = CreateOrderForm(initial=initial)


    # Обработка GET-запроса
    context = {
        'title': 'Спорт Лайн - Оформление заказа',
        'form': form,
        'orders': True,
    }
    return render(request, 'orders/create_order.html', context)

def qr_code(request, order_id):
    order = Order.objects.get(pk=order_id)  # Получение заказа по ID
    qr_image_url = order.qr_image.url if order.qr_image else None  # URL изображения QR-кода

    context = {
        'qr_image_url': qr_image_url,  # Передача URL изображения в контекст
    }

    return render(request, 'orders/qr_code.html', context)

orders/templates/orders/create_order.html
{% extends "base.html" %}
{% load static %}
{% load carts_tags %}

{% block content %}
<div class="container-fluid">
    <div class="row">
        <div class="col-lg-1 col-md-12">
        </div>
        <div class="col-lg-10 col-md-12">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-lg-12 col-md-12 mt-4">
                        <form action="{% url "orders:create_order" %}" method="post">
                            {% csrf_token %}
                            <div class="row justify-content-center">
                                <div class="col-lg-12 mb-4 text-center">
                                    <h2>Выбранные товары</h2>
                                </div>
                                <div class="container" id="cart-items-container">
                                    <!-- Разметка корзины -->
                                    {% user_carts request as carts %}
                                    {% include "carts/includes/included_cart.html" %}
                                    <!-- Закончилась разметка корзины -->
                                </div>
                                <div class="col-lg-12 col-md-12 mt-4">
                                    <div class="row justify-content-center">
                                        <div class="col-lg-12 text-center">
                                            <h2>Информация о заказе</h2>
                                        </div>
                                        <div class="card mt-4">
                                            <div class="card-body">
                                                <div class="name-good text-center mb-4">
                                                    <h4>Данные получателя</h4>
                                                </div>
                                                <div class="col-lg-12 mb-4">
                                                        <div class="row">
                                                            <div class="col-md-6 mb-3">
                                                                <label for="id_first_name" class="form-label">Имя*
                                                                </label>
                                                                <input type="text" class="form-control"
                                                                    id="id_first_name" 
                                                                    value="{% if form.first_name.value %}{{ form.first_name.value }}{% endif %}" 
                                                                    name="first_name"
                                                                    placeholder="Введите ваше имя пользователя"
                                                                    required>
                                                                {% if form.first_name.errors %}
                                                                    <div class="alert alert-danger alert-dismissible fade show">{{form.first_name.errors}}</div>
                                                                {% endif %}
                                                            </div>
                                                            <div class="col-md-6 mb-3">
                                                                <label for="id_last_name"
                                                                    class="form-label">Фамилия*</label>
                                                                <input type="text" class="form-control"
                                                                    id="id_last_name" 
                                                                    value="{% if form.last_name.value %}{{ form.last_name.value }}{% endif %}"
                                                                    name="last_name"
                                                                    placeholder="Введите вашу фамилию"
                                                                    required>
                                                                {% if form.last_name.errors %}
                                                                    <div class="alert alert-danger alert-dismissible fade show">{{form.last_name.errors}}</div>
                                                                {% endif %}
                                                            </div>
                                                            <div class="col-md-6 mb-3">
                                                                <label for="id_phone_number"
                                                                    class="form-label">Введите ваш телефон*</label>
                                                                <input type="text" class="form-control"
                                                                    id="id_phone_number" 
                                                                    value="{% if form.phone_number.value %}{{ form.phone_number.value }}{% endif %}"
                                                                    name="phone_number"
                                                                    placeholder="В формате: XXX-XXX-XX-XX"
                                                                    required>
                                                                {% if form.phone_number.errors %}
                                                                    <div class="alert alert-danger alert-dismissible fade show">{{form.phone_number.errors}}</div>
                                                                {% endif %}
                                                            </div>
                                                            <div class="col-md-6 mb-3">
                                                                <label for="id_email" class="form-label">Email*</label>
                                                                <input type="email" class="form-control" id="id_email"
                                                                value="{% if form.email.value %}{{ form.email.value }}{% endif %}"
                                                                name="email"
                                                                placeholder="Введите ваш email" required>
                                                            {% if form.email.errors %}
                                                                    <div class="alert alert-danger alert-dismissible fade show">{{form.email.errors}}</div>
                                                            {% endif %}
                                                            </div>
                                                        </div>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="card mt-4">
                                            <div class="card-body">
                                                <div class="name-good text-center mb-4">
                                                    <h4>Адрес доставки</h4>
                                                </div>
                                                <div class="card-body">
                                                    <p style="font-size: 20px; text-decoration: underline 1px;">Область доставки - <strong>г. Саратов</strong></p>
                                                    <p style="font-size: 20px; text-decoration: underline 1px;">Тип доставки - <strong>Курьер</strong></p>
                                                    <div class="name-good text-center mb-4">
                                                        <h4>Доставка</h4>
                                                    </div>
                                                    <div class="col-lg-12 mb-4">
                                                            <div class="col-lg-12 mb-4">
                                                                <h4>Адрес доставки</h4>
                                                            </div>
                                                            <div class="row">
                                                                <div class="col-md-6 mb-3">
                                                                    <label for="id_delivery_address" class="form-label">Улица, номер дома и квартира*
                                                                    </label>
                                                                    <input type="text" class="form-control"
                                                                        id="id_delivery_address"
                                                                        value="{% if form.delivery_address.value %}{{ form.delivery_address.value }}{% endif %}"
                                                                        name="delivery_address"
                                                                        placeholder="Ленина, дом 5а кв 185"
                                                                        required>
                                                                    {% if form.delivery_address.errors %}
                                                                        <div class="alert alert-danger alert-dismissible fade show">{{form.delivery_address.errors}}</div>
                                                                    {% endif %}
                                                                </div>
                                                                <div class="col-md-6 mb-3">
                                                                    <label for="id_comment" class="form-label">Комментарий курьеру
                                                                    </label>
                                                                    <input type="text" class="form-control"
                                                                        id="id_comment"
                                                                        value="{% if form.comment.value %}{{ form.comment.value }}{% endif %}"
                                                                        name="comment"
                                                                        placeholder="Оставьте у двери">
                                                                </div>
                                                            </div>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                    <div class="col-lg-2 mt-4">
                                        <button type="submit" class="btn btn-warning mb-4">Оформить заказ</button>
                                    </div>
                            </div>
                        </form>
                    </div>
                    <div class="col-lg-12 col-md-12 mt-4">
                        <div class="row justify-content-center">
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-lg-1 col-md-12">
            </div>
        </div>
    </div>
</div>
{% endblock %}

orders/templates/orders/qr_code.html
{% extends "base.html" %}

{% load static %}


{% block content %}
<body>
    <div class="container">
        <div class="row justify-content-center" style="margin-top: 50px;">
            <h2>Оплата через QR-код</h2>  <!-- Подпись -->
            <p>Пожалуйста, используйте банковское приложение для сканирования QR-кода и оплаты вашего заказа.</p>  <!-- Инструкции -->
            {% if qr_image_url %}
            <div style="border: 1px solid #ccc; padding: 10px; background-color: #f9f9f9; border-radius: 10px;">  <!-- Рамка -->
                <img src="{{ qr_image_url }}" alt="QR Code" style="max-width: 200px; max-height: 200px;">  <!-- Уменьшение размера -->
            </div>
            {% else %}
            <div>QR-код не найден.</div>
            {% endif %}
        </div>
    </div>
{% endblock %}