app/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static

from app import settings


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("main.urls", namespace="main")),
    path("", include("goods.urls", namespace="catalog")),
    path("", include("goods.urls", namespace="action")),
    path("", include("goods.urls", namespace="new_goods")),
    path("user/", include("users.urls", namespace="user")),
    path("cart/", include("carts.urls", namespace="cart")),
    path("orders/", include("orders.urls", namespace="orders")),
]


if settings.DEBUG:
    urlpatterns += [
        path("__debug__/", include("debug_toolbar.urls")),
    ]
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

goods/urls.py
from django.urls import path

from goods import views

app_name = 'goods'

urlpatterns = [
    path('', views.catalog, name='index'),
    path('search/', views.catalog_category, name='search'),
    path('product/<slug:product_slug>/', views.product, name='product'),
    path('catalog/', views.catalog, name='catalog'),
    path('action/', views.action, name='action'),
    path('new_goods/', views.new_goods, name='new_goods'),
    path('category/<slug:category_slug>/', views.catalog_category, name='category')
]

orders/urls.py
from django.urls import path
from orders import views

app_name = 'orders'

urlpatterns = [
    path('create_order/', views.create_order, name='create_order'),
    path('qr_code/<int:order_id>/', views.qr_code, name='qr_code'),
]

users/urls.py
from django.urls import path

from users import views

app_name = 'users'

urlpatterns = [
    path('login/', views.login, name='login'),
    path('registration/', views.registration, name='registration'),
    path('profile/', views.profile, name='profile'),
    path('logout/', views.logout, name='logout'),
    path('my_orders/', views.my_orders, name='my_orders'),
    path('users-cart/', views.users_cart, name='users_cart'),
]

orders/models.py
from django.db import models
from goods.models import Products

from users.models import User


class OrderitemQueryset(models.QuerySet):
    
    def total_price(self):
        return sum(cart.products_price() for cart in self)
    
    def total_quantity(self):
        if self:
            return sum(cart.quantity for cart in self)
        return 0

class Order(models.Model):
    first_name = models.CharField(max_length=150, verbose_name="Имя получателя", blank=True, null=True, default=None)
    last_name = models.CharField(max_length=150, verbose_name="Фамилия получателя", blank=True, null=True, default=None)
    user = models.ForeignKey(to=User, on_delete=models.SET_DEFAULT, blank=True, null=True, verbose_name="Пользователь", default=None)
    created_timestamp = models.DateTimeField(auto_now_add=True, verbose_name="Дата создания заказа")
    phone_number = models.CharField(max_length=20, verbose_name="Номер телефона")
    delivery_address = models.TextField(null=True, blank=True, verbose_name="Адрес доставки")
    is_paid = models.BooleanField(default=False, verbose_name="Оплачено")
    status = models.CharField(max_length=50, default='В обработке', verbose_name="Статус заказа")
    qr_image = models.ImageField(upload_to='qr_codes/', null=True, blank=True, verbose_name="QR-код")  # Новое поле для QR-кода
    comment = models.TextField(blank=True, null=True, verbose_name="Комментарий к заказу")
    email = models.EmailField(verbose_name="Email получателя", blank=True, null=True, default=None)

    class Meta:
        db_table = "order"
        verbose_name = "Заказ"
        verbose_name_plural = "Заказы"

    def __str__(self):
        if self.first_name and self.last_name:
            return f"Заказ № {self.pk} | Покупатель {self.first_name} {self.last_name}"
        else:
            return f"Заказ № {self.pk} | Покупатель {self.user.first_name} {self.user.last_name}"


class OrderItem(models.Model):
    order = models.ForeignKey(to=Order, on_delete=models.CASCADE, verbose_name="Заказ")
    product = models.ForeignKey(to=Products, on_delete=models.SET_DEFAULT, null=True, verbose_name="Продукт", default=None)
    name = models.CharField(max_length=150, verbose_name="Название")
    price = models.DecimalField(max_digits=7, decimal_places=2, verbose_name="Цена")
    quantity = models.PositiveIntegerField(default=0, verbose_name="Количество")
    created_timestamp = models.DateTimeField(auto_now_add=True, verbose_name="Дата продажи")


    class Meta:
        db_table = "order_item"
        verbose_name = "Проданный товар"
        verbose_name_plural = "Проданные товары"

    objects = OrderitemQueryset.as_manager()

    def products_price(self):
        return round(self.price * self.quantity, 2)

    def __str__(self):
        return f"Товар {self.name} | Заказ № {self.order.pk}"

users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


class User(AbstractUser):
    phone_number = models.CharField(max_length=10, blank=True, null=True)

    class Meta:
        db_table = "user"
        verbose_name = "Пользователя"
        verbose_name_plural = "Пользователи"

    def __str__(self):
        return self.username

users/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm, UserChangeForm
import re

from users.models import User


class UserLoginForm(AuthenticationForm):

    class Meta:
        model = User
        fields = ['username', 'password']
   
    username = forms.CharField()
    password = forms.CharField()

class UserRegistrationForm(UserCreationForm):
    class Meta:
        model = User
        fields = (
            "first_name",
            "last_name",
            "username",
            "email",
            "password1",
            "password2",
        )

    first_name = forms.CharField()
    last_name = forms.CharField()
    username = forms.CharField()
    email = forms.CharField()
    password1 = forms.CharField()
    password2 = forms.CharField()


class ProfileForm(UserChangeForm):
    class Meta:
        model = User
        fields = (
            "first_name",
            "last_name",
            "username",
            "email",
            "phone_number",
        )

    first_name = forms.CharField()
    last_name = forms.CharField()
    username = forms.CharField()
    email = forms.CharField()
    phone_number = forms.CharField()

    def clean_phone_number(self):
        data = self.cleaned_data['phone_number']
        
        if not data.isdigit():
            raise forms.ValidationError("Номер телефона должен содержать только цифры")
        
        pattern = re.compile(r'^\d{10}$')
        if not pattern.match(data):
            raise forms.ValidationError("Неверный формат номера. Номер должен состоять из 10 цифр.")
        
        return data

users/views.py
from django.contrib.auth.decorators import login_required
from django.db.models import Prefetch, Sum, F
from django.http import HttpResponseRedirect
from django.shortcuts import redirect, render
from django.contrib import auth, messages
from django.urls import reverse

from carts.models import Cart
from goods.models import Categories, Products
from orders.models import Order, OrderItem
from users.forms import ProfileForm, UserLoginForm, UserRegistrationForm


def login(request):
    categories = Categories.objects.all()  # Использование модели Categories
    action = Products.objects.filter(discount__gt=0, quantity__gt=0).order_by('?')[:3]
    new_goods = Products.objects.filter(new="Да", quantity__gt=0).order_by('?')[:3]
    if request.method == 'POST':
        form = UserLoginForm(data=request.POST)
        if form.is_valid():
            username = request.POST['username']
            password = request.POST['password']
            user = auth.authenticate(username=username, password=password)

            session_key = request.session.session_key

            if user:
                auth.login(request, user)
                messages.success(request, f"{username}, Вы вошли в аккаунт")

                if session_key:
                    Cart.objects.filter(session_key=session_key).update(user=user)

                return HttpResponseRedirect(reverse('main:index'))
        else:
            # Возвращаем страницу, которая содержит модальное окно, с контекстом, чтобы показать ошибки
            context = {
                'title': 'Спорт Лайн - Главная',
                'form': form,
                'categories': categories,
                'action': action,
                'new_goods': new_goods,
            }
            return render(request, 'main/index.html', context)  # Шаблон, который содержит модальное окно

def registration(request):
    categories = Categories.objects.all()  # Использование модели Categories
    action = Products.objects.filter(discount__gt=0, quantity__gt=0).order_by('?')[:3]
    new_goods = Products.objects.filter(new="Да", quantity__gt=0).order_by('?')[:3]
    if request.method == 'POST':
        form = UserRegistrationForm(data=request.POST)
        if form.is_valid():
            form.save()

            session_key = request.session.session_key

            user = form.instance
            auth.login(request, user)

            if session_key:
                    Cart.objects.filter(session_key=session_key).update(user=user)

            messages.success(request, f"{user.username}, Вы успешно зарегистрированны и вошли в аккаунт")
            return HttpResponseRedirect(reverse('main:index'))
        else:
            # Возвращаем страницу, которая содержит модальное окно, с контекстом, чтобы показать ошибки
            context = {
                'title': 'Спорт Лайн - Главная',
                'form': form,
                'categories': categories,
                'action': action,
                'new_goods': new_goods,
            }
            return render(request, 'main/index.html', context)  # Шаблон, который содержит модальное окно
@login_required
def profile(request):
    if request.method == 'POST':
        form = ProfileForm(data=request.POST, instance=request.user)
        if form.is_valid():
            form.save()
            messages.success(request, f" Профиль успешно обновлен ")
            return HttpResponseRedirect(reverse('user:profile'))
        else:
            # Возвращаем страницу, которая содержит модальное окно, с контекстом, чтобы показать ошибки
            context = {
                'form': form
            }
    else:
        form = ProfileForm(instance=request.user)

    context = {
        "title": "Спорт Лайн - Профиль", 
        'form': form,
    }
    return render(request, 'users/profile.html', context)  # Шаблон, который содержит модальное окно

@login_required
def logout(request):
    messages.success(request, f"{request.user.username}, Вы вышли из аккаунта")
    auth.logout(request)
    return redirect(reverse('main:index'))

def my_orders(request):

    if request.method == 'POST':
        form = ProfileForm(data=request.POST, instance=request.user)
        if form.is_valid():
            form.save()
            messages.success(request, f" Профиль успешно обновлен ")
            return HttpResponseRedirect(reverse('user:profile'))
        else:
            # Возвращаем страницу, которая содержит модальное окно, с контекстом, чтобы показать ошибки
            context = {
                'form': form
            }
    else:
        form = ProfileForm(instance=request.user)

    orders = (
            Order.objects.filter(user=request.user).prefetch_related(
                Prefetch(
                    'orderitem_set',
                    queryset=OrderItem.objects.select_related('product')
                )
            ).order_by('-id')
        )
    
    for order in orders:
        order.total_price = order.orderitem_set.aggregate(total=Sum(F('price') * F('quantity')))['total']

    context = {
        "title": "Спорт Лайн - Мои заказы", 
        'form': form,
        'orders': orders,
        }
    return render(request, "users/my_orders.html", context)

def users_cart(request):
    context = {
        "title": "Спорт Лайн - Корзина", 
        }
    return render(request, "users/users_cart.html", context)

users/templates/users/my_orders.html
{% extends "base.html" %}
{% load static %}
{% load carts_tags %}

{% block content %}
<div class="modal fade" id="exampleModalToggle" aria-hidden="true" aria-labelledby="exampleModalToggleLabel" tabindex="-1">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
            <div class="modal-header">
            <h1 class="modal-title fs-5" id="exampleModalToggleLabel">Авторизация</h1>
            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Закрыть"></button>
            </div>
            <div class="modal-body">
                <form>
                    <div class="row">
                        <div class="col-md-12 mb-3">
                            <label for="username" class="form-label">Имя пользователя*</label>
                            <input type="text" class="form-control" id="firstName"
                                placeholder="Введите ваше имя пользователя" required>
                        </div>
                        <div class="col-md-12 mb-3">
                            <label for="password1" class="form-label">Пароль*</label>
                            <input type="password" class="form-control" id="lastName"
                                placeholder="Введите ваш пароль" required>
                        </div>
                    </div>
                    <div class="container-fluid btn-position btn-regstration">
                        <div class="btn-row">
                            <div class="col-lg-2">
                                <button type="button"
                                    class="btn btn-primary mt-2 mb-2">Войти</button>
                            </div>
                        </div>
                    </div>
                </form>
            </div>
            <div class="modal-footer">
            <button class="btn btn-warning" data-bs-target="#exampleModalToggle2" data-bs-toggle="modal">Регистрация</button>
            </div>
        </div>
    </div>
</div>
<div class="modal fade" id="exampleModalToggle2" aria-hidden="true" aria-labelledby="exampleModalToggleLabel2" tabindex="-1">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
        <div class="modal-header">
            <h1 class="modal-title fs-5" id="exampleModalToggleLabel2">Регистрация</h1>
            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Закрыть"></button>
        </div>
        <div class="modal-body">
            <form>
                <div class="row">
                    <div class="col-md-6 mb-3">
                        <label for="firstName" class="form-label">Имя*</label>
                        <input type="text" class="form-control" id="firstName"
                            placeholder="Введите ваше имя" required>
                    </div>
                    <div class="col-md-6 mb-3">
                        <label for="lastName" class="form-label">Фамилия*</label>
                        <input type="text" class="form-control" id="lastName"
                            placeholder="Введите вашу фамилию" required>
                    </div>
                    <div class="col-md-6 mb-3">
                        <label for="username" class="form-label">Имя пользователя*</label>
                        <input type="text" class="form-control" id="username"
                            placeholder="Введите ваше имя пользователя" required>
                    </div>
                    <div class="col-md-6 mb-3">
                        <label for="email" class="form-label">Email*</label>
                        <input type="email" class="form-control" id="email"
                            placeholder="Введите ваш email" required>
                    </div>
                    <div class="col-md-6 mb-3">
                        <label for="password1" class="form-label">Пароль*</label>
                        <input type="password" class="form-control" id="password1"
                            placeholder="Введите пароль" required>
                    </div>
                    <div class="col-md-6 mb-3">
                        <label for="password2" class="form-label">Подтверждение пароля*</label>
                        <input type="password" class="form-control" id="password2"
                            placeholder="Подтвердите пароль" required>
                    </div>
                </div>
                <div class="container-fluid btn-position btn-regstration">
                    <div class="btn-row">
                        <div class="col-lg-2">
                            <button type="button"
                                class="btn btn-primary mt-4 mb-4">Зарегистрироваться</button>
                        </div>
                        <div class="col-lg-10"></div>
                    </div>
                </div>
            </form>
        </div>
        <div class="modal-footer">
            <button class="btn btn-warning" data-bs-target="#exampleModalToggle" data-bs-toggle="modal">Авторизация</button>
        </div>
        </div>
    </div>
</div>

<div class="container-fluid">
    <div class="row">
        <div class="col-lg-1 col-md-12">
        </div>
        <div class="col-lg-10 col-md-12">
            <div class="nav-bar-bottom-profile">
                <ul class="nav mt-2 info-profile">
                    <li class="nav-item">
                        <a class="nav-link action" href="{% url "user:profile" %}">Мой профиль</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link action" href="{% url "user:my_orders" %}">Мои заказы</a>
                    </li>
                    {% if user.is_authenticated and user.is_superuser %} 
                    <li class="nav-item">
                        <a class="nav-link action" href="{% url "admin:index" %}">Админ панель</a>
                    </li>
                    {% endif %}
                </ul>
            </div>
            <div class="col-lg-1 col-md-12">
            </div>
        </div>
    </div>
</div>
<div class="container-fluid">
    <div class="row">
        <div class="row justify-content-center">
            <div class="col-lg-1 col-md-12">
            </div>
            <div class="col-lg-10 col-md-12">
                <div class="col-lg-12 mb-4 text-center">
                    <h2>Мои заказы</h2>
                </div>
                <div class="card content-shop-cat mt-4">
                    <div class="accordion accordion-group-flush" id="accordionFlushExample">
                        {% for order in orders %}
                        <div class="accordion-item">
                            <div class="name-good bg-body-tertiary">
                                <h2 class="accordion-header" id="{{ order.id }}">
                                    <button class="accordion-button {% if order != orders.0 %}collapsed{% endif %}" type="button"
                                        data-bs-toggle="collapse" data-bs-target="#collapse{{ order.id }}"
                                        aria-expanded="false" aria-controls="collapse{{ order.id }}">
                                        Заказ {{ order.id }} - {{ order.created_timestamp }} | Статус: <strong class="mx-2"> {{order.status}} </strong>
                                    </button>
                                </h2>
                            </div>
                            <div id="collapse{{ order.id }}" class="accordion-collapse collapse {% if order == orders.0 %}show{% endif %}" aria-labelledby="heading{{ order.id }}" data-bs-parent="#accordionExample">
                                <div class="accordion-body">
                                    <div class="table-responsive">
                                        <table class="table" class="table table-striped">
                                            <thead>
                                                <tr>
                                                    <th scope="col">Товар</th>
                                                    <th scope="col">Количество</th>
                                                    <th scope="col">Цена</th>
                                                    <th scope="col">Общая стоимость</th>
                                                </tr>
                                            </thead>
                                            <tbody>
                                                {% for item in order.orderitem_set.all %}
                                                <tr>
                                                    <td><a class="text-dark" href="{% url 'goods:product' item.product.slug %}">{{ item.product.name }}</a></td>
                                                    <td>{{ item.quantity }}</td>
                                                    <td>{{ item.price }} ₽</td>
                                                    <td>{{ item.products_price }} ₽</td>
                                                </tr>
                                                {% endfor %}
                                            </tbody>
                                        </table>
                                        <div class="d-flex justify-content-between">
                                            <p class="p-0 m-0"><strong>Итого</strong></p>
                                            <p class="p-0 m-0"><strong>{{ order.total_price }} ₽</strong></p>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        {% endfor %}
                    </div>
                </div>
            </div>
            <div class="col-lg-1 col-md-12">
            </div>
        </div>
    </div>
</div>
{% endblock content %}

users/templates/users/profile.html
{% extends "base.html" %}
{% load static %}

{% block content %}
<div class="container-fluid">
    <div class="row">
        <div class="col-lg-1 col-md-12">
        </div>
        <div class="col-lg-10 col-md-12">
            <div class="nav-bar-bottom-profile">
                <ul class="nav mt-2 info-profile">
                    <li class="nav-item">
                        <a class="nav-link action" href="{% url "user:profile" %}">Мой профиль</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link action" href="{% url "user:my_orders" %}">Мои заказы</a>
                    </li>
                    {% if user.is_authenticated and user.is_superuser %} 
                    <li class="nav-item">
                        <a class="nav-link action" href="{% url "admin:index" %}">Админ панель</a>
                    </li>
                    {% endif %}
                </ul>
            </div>
            <div class="container-fluid">
                <div class="row">
                    <div class="col-lg-9 col-md-12">
                        <div class="row justify-content-center">
                            <h2 class="mb-4 mt-4">Личные данные</h2>
                            <form action="{% url "users:profile" %}" method="post">
                                {% csrf_token %}
                                <div class="row">
                                    <div class="col-md-9 mb-3">
                                        <label for="id_first_name" class="form-label">Имя*</label>
                                        <input type="text" class="form-control" 
                                        id="id_first_name"
                                        name="first_name"
                                        placeholder="Введите ваше имя" 
                                        value="{{ form.first_name.value }}"
                                        required>
                                        {% if form.first_name.errors %}
                                        <div class="alert alert-danger alert-dismissible fade show">{{form.first_name.errors}}</div>
                                        {% endif %}
                                    </div>
                                    <div class="col-md-9 mb-3">
                                        <label for="id_last_name" class="form-label">Фамилия*</label>
                                        <input type="text" class="form-control" 
                                        id="last_name"
                                        name="last_name"
                                        placeholder="Введите вашу фамилию" 
                                        value="{{ form.last_name.value }}"
                                        required>
                                        {% if form.last_name.errors %}
                                        <div class="alert alert-danger alert-dismissible fade show">{{form.last_name.errors}}</div>
                                        {% endif %}
                                    </div>
                                    <div class="col-md-9 mb-3">
                                        <label for="id_username" class="form-label">Имя пользователя*</label>
                                        <input type="text" class="form-control" 
                                        id="id_username"
                                        name="username"
                                        placeholder="Введите ваше имя пользователя" 
                                        value="{{ form.username.value }}"
                                        required>
                                        {% if form.username.errors %}
                                        <div class="alert alert-danger alert-dismissible fade show">{{form.username.errors}}</div>
                                        {% endif %}
                                    </div>
                                    <div class="col-md-9 mb-3">
                                        <label for="id_email" class="form-label">Email*</label>
                                        <input type="email" class="form-control" 
                                        id="id_email"
                                        name="email"
                                        placeholder="Введите ваш email" 
                                        value="{{ form.email.value }}"
                                        required>
                                        {% if form.email.errors %}
                                        <div class="alert alert-danger alert-dismissible fade show">{{form.email.errors}}</div>
                                        {% endif %}
                                    </div>
                                    <div class="col-md-9 mb-3">
                                        <label for="id_phone_number" class="form-label">Номер телефона*</label>
                                        <input type="text" class="form-control" 
                                        id="id_phone_number"
                                        name="phone_number"
                                        placeholder="В формате: XXX-XXX-XX-XX" 
                                        value="{{ form.phone_number.value }}"
                                        required>
                                        {% if form.phone_number.errors %}
                                            <div class="alert alert-danger alert-dismissible fade show">{{form.phone_number.errors}}</div>
                                        {% endif %}
                                    </div>
                                </div>
                                <div class="container-fluid btn-position btn-regstration">
                                    <div class="btn-row">
                                        <div class="col-lg-2">
                                            <button type="submit"
                                                class="btn btn-primary mt-2 mb-2">Сохранить</button>
                                            <a type="submit"
                                                class="btn btn-danger mt-2 mb-2" href="{% url "user:logout" %}">Выйти</a>
                                        </div>
                                    </div>
                                </div>
                            </form>
                            <div class="col-lg-5 col-md-12">
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-8 col-md-12 mt-4">
                    </div>
                </div>
            </div>
            <div class="col-lg-1 col-md-12">
            </div>
        </div>
    </div>
</div>
{% endblock content %}

users/templates/users/users_cart.html
{% extends "base.html" %}
{% load static %}
{% load carts_tags %}
{% user_carts request as carts %}
{% block content %}
<div class="container-fluid">
    <div class="row">
        <div class="col-lg-1">
        </div>
        <div class="card col-lg-10">
            <div class="container-fluid mt-4">
                <div class="row">
                    <div class="col-lg-12">
                        <h3>Корзина</h3>
                        <div class="container" id="cart-items-container">
                            <!-- Разметка корзины -->
                            {% include "carts/includes/included_cart.html" %}
                            <!-- Закончилась разметка корзины -->
                        </div>
                    </div>  
                    <div class="container-fluid btn-position">
                        <div class="btn-row">
                            <input type="hidden" id="user-authenticated" value="{{ request.user.is_authenticated }}" />
                            {% if carts %}               
                            <div class="col-lg-2">
                                <a href="{% url "orders:create_order" %}"><button type="button" class="btn btn-warning mb-4" id="checkout-button">Оформить заказ</button></a>
                            </div>
                            {% endif %}
                            <div class="col-lg-10">
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-lg-1">
        </div>
    </div>
</div>
{% endblock %}