app/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static

from app import settings


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("main.urls", namespace="main")),
    path("", include("goods.urls", namespace="catalog")),
    path("", include("goods.urls", namespace="action")),
    path("", include("goods.urls", namespace="new_goods")),
    path("user/", include("users.urls", namespace="user")),
    path("cart/", include("carts.urls", namespace="cart")),
    path("orders/", include("orders.urls", namespace="orders")),
]


if settings.DEBUG:
    urlpatterns += [
        path("__debug__/", include("debug_toolbar.urls")),
    ]
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

carts/urls.py
from django.urls import path

from carts import views

app_name = 'carts'

urlpatterns = [
    path('cart_add/', views.cart_add, name='cart_add'),
    path('cart_change/', views.cart_change, name='cart_change'),
    path('cart_remove/', views.cart_remove, name='cart_remove'),
]

goods/urls.py
from django.urls import path

from goods import views

app_name = 'goods'

urlpatterns = [
    path('', views.catalog, name='index'),
    path('search/', views.catalog_category, name='search'),
    path('product/<slug:product_slug>/', views.product, name='product'),
    path('catalog/', views.catalog, name='catalog'),
    path('action/', views.action, name='action'),
    path('new_goods/', views.new_goods, name='new_goods'),
    path('category/<slug:category_slug>/', views.catalog_category, name='category')
]

main/urls.py
from django.urls import path

from main import views

app_name = 'main'

urlpatterns = [
    path('', views.index, name='index'),
    path('about/', views.about, name='about'),
    path('contact/', views.handle_contact_form, name='contact'),  # Обработчик формы обратной связи
]

main/forms.py
# main/forms.py
from django import forms

class ContactForm(forms.Form):
    name = forms.CharField(min_length=2, widget=forms.TextInput(attrs={'placeholder': 'Ваше имя', 'class': 'form-control'}))
    email = forms.EmailField(widget=forms.EmailInput(attrs={'placeholder': 'Введите ваш email', 'class': 'form-control'}))
    message = forms.CharField(widget=forms.Textarea(attrs={'placeholder': 'Ваше сообщение', 'class': 'form-control'}))

main/views.py
from django.http import JsonResponse
from django.shortcuts import redirect, render
from goods.models import Categories, Products
from .forms import ContactForm
from django.contrib import messages
from django.core.mail import send_mail

def index(request):
    categories = Categories.objects.all()  # Использование модели Categories
    action = Products.objects.filter(discount__gt=0, quantity__gt=0).order_by('?')[:3]
    new_goods = Products.objects.filter(new="Да", quantity__gt=0).order_by('?')[:3]
    context = {
        'title': 'Спорт Лайн - Главная',
        'categories': categories,
        'action': action,
        'new_goods': new_goods,
    }
    return render(request, 'main/index.html', context)

def about(request):
    context = {
        'title': 'Спорт Лайн - О нас'
    }
    return render(request, 'main/about.html', context)



def send_contact_email(name, email, message):
    subject = "Сообщение с вашего сайта"
    body = f"Сообщение от {name} ({email}):\n\n{message}"
    from_email = 'TiMe2003R@yandex.ru'  # Адрес электронной почты отправителя
    to_email = 'TiMe2003R@yandex.ru'  # Адрес электронной почты, куда придет письмо
    
    send_mail(
        subject,
        body,
        from_email, 
        [to_email], 
        fail_silently=False
    )

def handle_contact_form(request):
    if request.method == 'POST':
        form = ContactForm(request.POST)
        if form.is_valid():
            name = form.cleaned_data['name']
            email = form.cleaned_data['email']
            message = form.cleaned_data['message']
            send_contact_email(name, email, message)
            return JsonResponse({'success': True})  # Отправляем успех в ответ на AJAX-запрос
        else:
            # Отправляем ошибки в формате JSON
            errors = {field: error for field, error in form.errors.items()}
            return JsonResponse({'success': False, 'errors': errors}, status=400)
    else:
        form = ContactForm()  # Создаем новую форму для GET-запроса
        return render(request, 'main/contact_form.html', {'form': form})
    

main/templates/main/about.html
{% extends "base.html" %}

{% load static %}


{% block content %}
    <div class="about">
    <div class="container-fluid mt-4">
        <div class="row">
            <div class="col-lg-1 col-md-12">
            </div>
            <div class="col-lg-10 col-md-12">
                <h2>О компании</h2>
                <p>
                    Основной деятельностью интернет-магазина СпортЛайн является
                    предоставление клиентам широкого ассортимента спортивных товаров,
                    охватывающих различные виды физической активности. Магазин
                    стремится удовлетворить потребности клиентов в высококачественной
                    спортивной экипировке, одежде и аксессуарах для самых разнообразных
                    видов спорта.
                </p>
                <p>
                    В рамках своей деятельности предоставляет не только продукцию,
                    но и создает уникальный опыт для клиентов. Магазин стремится стать
                    надежным партнером для любителей активного образа жизни, предлагая
                    товары от ведущих мировых брендов и обеспечивая высокий уровень
                    обслуживания.
                </p>
                <p>
                    Организация активно участвует в спортивных мероприятиях и
                    инициативах, поддерживая и поощряя здоровый образ жизни. Кроме того,
                    магазин регулярно обновляет свой ассортимент, следя за последними
                    тенденциями в мире спортивной индустрии, чтобы удовлетворять
                    потребности даже самых требовательных клиентов.
                </p>
                <p>
                    В целях эффективной организации деятельности, магазин
                    использует современные методы управления и технологии, стремясь
                    постоянно совершенствовать свои бизнес-процессы.
                </p>
            </div>
            <div class="col-lg-1 col-md-12">
            </div>
        </div>
    </div>
    </div>
{% endblock %}

main/templates/main/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet">
  <link rel="stylesheet" href="{% static "deps/styles/my_css.css" %}">
  <link rel="apple-touch-icon" sizes="180x180" href="{% static "deps/files/favicon_io/apple-touch-icon.png" %}">
  <link rel="icon" type="image/png" sizes="32x32" href="{% static "deps/files/favicon_io/favicon-32x32.png" %}">
  <link rel="icon" type="image/png" sizes="16x16" href="{% static "deps/files/favicon_io/favicon-16x16.png" %}">
  <link rel="manifest" href="{% static "deps/files/favicon_io/site.webmanifest" %}">
  <title>{{ title }}</title>
</head>

<body>
  <header>
    <div class="container-fluid mt-4">
      <div class="row">
        <div class="col-lg-1 col-md-12">
        </div>
        <div class="col-lg-10 col-md-12">
          <nav class="navbar navbar-expand-lg bg-body-tertiary">
            <div class="container-fluid">
              <a class="navbar-brand" href="{% url "main:index" %}"><img src="{% static "deps/images/logo.svg" %}" alt="logo"></a>
              <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false"
                aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
              </button>
              <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                  <li class="nav-item">
                    <a class="nav-link" href="{% url "catalog:catalog" %}">Каталог</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" data-bs-target="#exampleModalToggle" data-bs-toggle="modal">
                      <img src="{% static "deps/images/login in.svg" %}" alt="" width="26" height="26">
                    </a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="profile.html"><img src="{% static "deps/images/profile.svg" %}" alt="" width="26"
                        height="26"></a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="shopping_cat.html"><img src="{% static "deps/images/shopping cart.svg" %}" alt=""
                        width="24" height="24"></a>
                  </li>
                </ul>
                <form class="d-flex" role="search" action="{% url "goods:search" %}" method="get">
                  <input class="form-control me-2" type="search" placeholder="Поиск" name="q" aria-label="Search">
                  <button class="btn btn-outline-success btn-color btn-color" type="submit"><img
                      src="{% static "deps/images/search.svg" %}" alt="" width="20" height="20"></button>
                </form>
              </div>
            </div>
          </nav>
          <div class="nav-bar-bottom">
            <ul class="nav justify-content-between mt-2">
              <li class="nav-item">
                <a class="nav-link" href="{% url 'goods:action' %}">Акции</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'goods:new_goods' %}">Новинки</a>
              </li>
              {% for category in catalog %}
                <li class="nav-item">
                  <a class="nav-link" href="{% url "goods:category" category.slug %}">{{ category.name }}</a>
                </li>
              {% endfor %}
            </ul>
          </div>
        </div>
        <div class="col-lg-1">
        </div>
      </div>
    </div>
  </header>

  <section>
    <div class="modal fade" id="exampleModalToggle" aria-hidden="true" aria-labelledby="exampleModalToggleLabel"
      tabindex="-1">
      <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
          <div class="modal-header">
            <h1 class="modal-title fs-5" id="exampleModalToggleLabel">Авторизация</h1>
            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Закрыть"></button>
          </div>
          <div class="modal-body">
            <form>
              <div class="row">
                <div class="col-md-12 mb-3">
                  <label for="username" class="form-label">Имя пользователя*</label>
                  <input type="text" class="form-control" id="firstName" placeholder="Введите ваше имя пользователя"
                    required>
                </div>
                <div class="col-md-12 mb-3">
                  <label for="password1" class="form-label">Пароль*</label>
                  <input type="password" class="form-control" id="password1" placeholder="Введите пароль" required>
                </div>
              </div>
              <div class="container-fluid btn-position btn-regstration">
                <div class="btn-row">
                  <div class="col-lg-2">
                    <button type="button" class="btn btn-primary mt-2 mb-2">Войти</button>
                  </div>
                </div>
              </div>
            </form>
          </div>
          <div class="modal-footer">
            <button class="btn btn-warning" data-bs-target="#exampleModalToggle2"
              data-bs-toggle="modal">Регистрация</button>
          </div>
        </div>
      </div>
    </div>
    <div class="modal fade" id="exampleModalToggle2" aria-hidden="true" aria-labelledby="exampleModalToggleLabel2"
      tabindex="-1">
      <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
          <div class="modal-header">
            <h1 class="modal-title fs-5" id="exampleModalToggleLabel2">Регистрация</h1>
            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Закрыть"></button>
          </div>
          <div class="modal-body">
            <form>
              <div class="row">
                <div class="col-md-6 mb-3">
                  <label for="firstName" class="form-label">Имя*</label>
                  <input type="text" class="form-control" id="firstName" placeholder="Введите ваше имя" required>
                </div>
                <div class="col-md-6 mb-3">
                  <label for="lastName" class="form-label">Фамилия*</label>
                  <input type="text" class="form-control" id="lastName" placeholder="Введите вашу фамилию" required>
                </div>
                <div class="col-md-6 mb-3">
                  <label for="username" class="form-label">Имя пользователя*</label>
                  <input type="text" class="form-control" id="username" placeholder="Введите ваше имя пользователя"
                    required>
                </div>
                <div class="col-md-6 mb-3">
                  <label for="email" class="form-label">Email*</label>
                  <input type="email" class="form-control" id="email" placeholder="Введите ваш email" required>
                </div>
                <div class="col-md-6 mb-3">
                  <label for="password1" class="form-label">Пароль*</label>
                  <input type="password" class="form-control" id="password1" placeholder="Введите пароль" required>
                </div>
                <div class="col-md-6 mb-3">
                  <label for="password2" class="form-label">Подтверждение пароля*</label>
                  <input type="password" class="form-control" id="password2" placeholder="Подтвердите пароль" required>
                </div>
              </div>
              <div class="container-fluid btn-position btn-regstration">
                <div class="btn-row">
                  <div class="col-lg-2">
                    <button type="button" class="btn btn-primary mt-4 mb-4">Зарегистрироваться</button>
                  </div>
                  <div class="col-lg-10"></div>
                </div>
              </div>
            </form>
          </div>
          <div class="modal-footer">
            <button class="btn btn-warning" data-bs-target="#exampleModalToggle"
              data-bs-toggle="modal">Авторизация</button>
          </div>
        </div>
      </div>
    </div>

    {% block content %}

    {% endblock %}

    <!-- Modal -->
    <div class="modal fade" id="staticBackdrop" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
        <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h1 class="modal-title fs-5" id="staticBackdropLabel">Напишите нам</h1>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
            <form>
                <div class="row">
                    <div class="col-md-12 mb-3">
                        <label for="username" class="col-form-label">Текст сообщения:</label>
                        <input type="text" class="form-control" id="Message"
                            placeholder="Сообщение" required>
                    </div>
                    <div class="col-md-6 mb-3">
                        <label for="password1" class="form-label">Имя:</label>
                        <input type="text" class="form-control" id="Name"
                            placeholder="Введите ваше имя" required>
                    </div>
                    <div class="col-md-6 mb-3">
                        <label for="password1" class="form-label">Email:</label>
                        <input type="text" class="form-control" id="Email"
                            placeholder="Введите ваш Email" required>
                    </div>
                </div>
                <div class="container-fluid btn-position btn-regstration">
                    <div class="btn-row">
                        <div class="col-lg-2">
                            <button type="button"
                                class="btn btn-warning mt-2 mb-2">Отправить</button>
                        </div>
                        <div class="col-lg-10 link-login">
                            <div class="social-network-link">
                                Наши социальные сети:
                                <a href="https://t.me/Timofei2003"><img style="width: 28px; margin-inline: 0.5em;"
                                    src="{% static "deps/images/TG.png" %}" alt="TG"></a>
                                <a href="https://vk.com/tim3002"><img style="width: 46px;"
                                    src="{% static "deps/images/VK.png" %}" alt="VK"></a>
                            </div>
                            <div class="number-phone mt-2">
                                <p>Наш телефон: +7-927-622-38-73</p>
                            </div>
                        </div>
                    </div>
                </div>
            </form>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-primary" data-bs-dismiss="modal">Закрыть</button>
        </div>
      </div>
        </div>
    </div>
  </section>

  <footer>
    <div class="container-fluid">
      <div class="row">
        <div class="col-lg-4 col-md-12 footer-text text-center">
          <a href="{% url "main:index" %}"><img src="{% static "deps/images/logo.svg" %}" alt="logo"></a>
          <p>Политика конфиденциальности</p>
          <p>Все права защищены. 2024</p>
        </div>
        <div class="col-lg-4 col-md-12 footer-text text-center media-links">
          <div class="footer-about">
            <p><a href="{% url "main:about" %}">О наc</a></p>
            <a class="nav-link-footer" data-bs-toggle="modal" data-bs-target="#staticBackdrop">
              <p>Напишите нам</p>
            </a>
            </p>
          </div>
        </div>
        <div class="col-lg-4 col-md-12 media-links">
          <a href="https://t.me/Timofei2003"><img style="width: 32px; margin-inline: 1em;" src="{% static "deps/images/TG.png" %}"
              alt="TG"></a>
          <a href="https://vk.com/tim3002"><img style="width: 50px; margin-inline: 1em;" src="{% static "deps/images/VK.png" %}"
              alt="VK"></a>
        </div>
      </div>
    </div>
  </footer>

  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz"
    crossorigin="anonymous"></script>

</body>

</html>

main/templates/main/index.html
{% extends "base.html" %}
{% load static %}
{% block content %}
    <div class="section-carousel">
      <div class="container-fluid mt-4">
        <div class="row">
          <div class="col-lg-1 col-md-12"></div>
          <div class="col-lg-10 col-md-12">
            <div class="row">
              <div id="carouselExampleIndicators" class="carousel slide" data-bs-ride="carousel" data-bs-interval="3000">
                <div class="carousel-indicators">
                  <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="0" class="active"
                    aria-current="true" aria-label="Slide 1"></button>
                  <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="1"
                    aria-label="Slide 2"></button>
                  <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="2"
                    aria-label="Slide 3"></button>
                </div>
                <div class="carousel-inner">
                  <div class="carousel-item active">
                    <a href="{% url 'goods:new_goods' %}"><img src="{% static "deps/images/newCollection.jpg" %}" class="d-block w-100"
                        alt="..."></a>
                  </div>
                  {% for category in catalog %}
                    {% if category.slug == 'balls' %}
                        <div class="carousel-item">
                            <a href="{% url 'goods:category' category.slug %}">
                                <img src="{% static "deps/images/Мячи_реклама_3.jpg" %}" class="d-block w-100" alt="...">
                            </a>
                        </div>
                    {% elif category.slug == 'krossovki' %}
                        <div class="carousel-item">
                            <a href="{% url 'goods:category' category.slug %}">
                                <img src="{% static "deps/images/Кроссовки_реклама_2.jpg" %}" class="d-block w-100" alt="...">
                            </a>
                        </div>
                    {% endif %}
                  {% endfor %}
                </div>
                <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleIndicators"
                  data-bs-slide="prev">
                  <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                  <span class="visually-hidden">Previous</span>
                </button>
                <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleIndicators"
                  data-bs-slide="next">
                  <span class="carousel-control-next-icon" aria-hidden="true"></span>
                  <span class="visually-hidden">Next</span>
                </button>
              </div>
            </div>
          </div>
          <div class="col-lg-1"></div>
        </div>
      </div>
    </div>

    <div class="section-action">
      <div class="container-fluid mt-4">
        <div class="row">
          <div class="col-lg-1 col-md-12">
          </div>
          <div class="col-lg-10 col-md-12">
            <div class="action-text">
              <h2><a href="{% url 'goods:action' %}">Акции</a></h2>
            </div>
          </div>
          <div class="col-lg-1 col-md-12">
          </div>
          <div class="container-fluid mt-2">
            <div class="row">
              <div class="col-lg-1 col-md-12">
              </div>
              <div class="col-lg-10 col-md-12">
                <div class="row">
                  {% for product in action %}
                    <div class="col-lg-4 col-md-6 mt-4">
                      <div class="card custom-shadow">
                          <a href="{% url "catalog:product" product.slug %}">
                              <img src="{{ product.image.url }}" class="card-img-top" alt="{{ product.name }}">
                          </a>
                          <div class="card-body">
                              <span class="badge bg-warning text-dark">Скидка {{ product.discount }}%</span>
                              <a href="{% url "catalog:product" product.slug %}">
                                  <h5 class="card-title">{{ product.name }}</h5>
                              </a>
                              <a href="{% url "catalog:product" product.slug %}">
                                  <div class="text-truncate-container">
                                      <p class="card-text">{{ product.description }}</p>
                                  </div>
                              </a>
                          </div>
                          <ul class="list-group list-group-flush">
                              <li class="list-group-item">id: {{ product.display_id }}</li>
                              {% if product.quantity > 0 %}
                                  <li class="list-group-item">В наличии: {{ product.quantity }}</li>
                              {% else %}
                                  <li class="list-group-item text-danger">Нет в наличии</li>
                              {% endif %}
                          </ul>
                          <div class="d-flex justify-content-between">
                              <p><s>{{ product.price }}₽</s></p>
                              <p><strong>{{ product.sell_price }}₽</strong></p>
                              {% if product.quantity > 0 %}
                                  <a href="{% url "cart:cart_add" %}" class="btn btn add-to-cart" data-product-id="{{ product.id }}">
                                      {% csrf_token %}
                                      <img class="mx-1" src="{% static "deps/images/basket.svg" %}" alt="Catalog Icon" width="32" height="32">
                                  </a>
                              {% endif %}
                          </div>
                      </div>
                    </div>
                  {% endfor %}
                </div>
              </div>
            </div>
            <div class="col-lg-1">
            </div>
          </div>
        </div>
      </div>
    </div>

    <div class="section-new">
      <div class="container-fluid mt-4">
        <div class="row">
          <div class="col-lg-1 col-md-12">
          </div>
          <div class="col-lg-10 col-md-12">
            <div class="action-text">
              <h2><a href="{% url 'goods:new_goods' %}">Новинки</a></h2>
            </div>
          </div>
          <div class="col-lg-1 col-md-12">
          </div>
          <div class="container-fluid mt-4">
            <div class="row">
              <div class="col-lg-1 col-md-12">
              </div>
              <div class="col-lg-10 col-md-12">
                <div class="row">
                  {% for product in new_goods %}
                  <div class="col-lg-4 col-md-6 mt-4">
                    <div class="card custom-shadow">
                        <a href="{% url "catalog:product" product.slug %}"><img src="{{ product.image.url }}" class="card-img-top" alt="{{ product.image }}"></a>
                        <div class="card-body">
                            <span class="badge bg-info text-dark">Новинка</span>
                            <a href="{% url "catalog:product" product.slug %}">
                                <h5 class="card-title">{{ product.name }}</h5>
                            </a>
                            <a href="{% url "catalog:product" product.slug %}">
                                <div class="text-truncate-container">
                                    <p class="card-text">{{ product.description }}</p>
                                </div>
                            </a>
                        </div>
                        <ul class="list-group list-group-flush">
                            <li class="list-group-item">id: {{ product.display_id }}</li>
                            {% if product.quantity > 0 %}
                                <li class="list-group-item">В наличии: {{ product.quantity }}</li>
                            {% else %}
                                <li class="list-group-item text-danger">Нет в наличии</li>
                            {% endif %}
                        </ul>
                        <div class="d-flex justify-content-between">
                            <p><strong>{{ product.price }}₽</strong></p>
                            {% if product.quantity > 0 %}
                                <a href="{% url "cart:cart_add" %}" class="btn add-to-cart" data-product-id="{{ product.id }}">
                                    {% csrf_token %}
                                    <img class="mx-1" src="{% static "deps/images/basket.svg" %}" alt="Catalog Icon" width="32" height="32">
                                </a>
                            {% endif %}
                        </div>
                    </div>
                  </div>
                  {% endfor %}
                </div>
                <div class="col-lg-1">
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
{% endblock %}